name = "lucrental-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "lucrental-db"
database_id = "839534bb-9ecc-429b-9011-757f73b0e274"

# R2 Storage for images
[[r2_buckets]]
binding = "IMAGES"
bucket_name = "lucrental-images"

[vars]
CORS_ORIGIN = "*"
